2019-09-07 12:15:39,140 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 12:44:41,737 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 12:45:05,467 ERROR: Exception on /reset_password_request [POST] [in C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\xampp\htdocs\microblog\app\routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "C:\xampp\htdocs\microblog\app\email.py", line 29, in send_password_reset_email
    user=user, token=token))
  File "C:\xampp\htdocs\microblog\app\email.py", line 16, in send_email
    mail.send(msg)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2019-09-07 12:46:12,497 ERROR: Exception on /reset_password_request [POST] [in C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\xampp\htdocs\microblog\app\routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "C:\xampp\htdocs\microblog\app\email.py", line 29, in send_password_reset_email
    user=user, token=token))
  File "C:\xampp\htdocs\microblog\app\email.py", line 16, in send_email
    mail.send(msg)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\Sandip\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2019-09-07 12:46:22,437 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 12:56:42,923 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 13:12:06,892 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 13:22:40,737 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 13:23:15,500 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 13:25:49,985 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 13:27:31,746 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-11 20:27:50,582 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:28:45,798 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:31:22,774 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:31:57,421 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:37:23,730 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:38:36,867 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:39:12,023 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:43:39,029 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:46:12,762 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 20:56:53,798 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 21:07:57,525 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 21:48:04,668 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-11 21:49:56,723 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:48:31,691 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:49:18,215 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:52:54,862 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:53:14,801 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:55:20,898 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:55:40,555 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:57:26,137 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:57:46,659 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:58:00,274 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
2019-09-13 12:58:14,744 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:55]
